# Chapter 6

In [1]:
L2 = [True, '2', 3.0, 4]
L2

[True, '2', 3.0, 4]

In [2]:
[type(item) for item in L2]

[bool, str, float, int]

In [3]:
for item in L2:
    print(type(item))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [4]:
import numpy as np

In [5]:
np.random.seed(123) 
x1 = np.random.randint(10, size=6)
x1 # 1차원

array([2, 2, 6, 1, 3, 9])

In [6]:
x2 = np.random.randint(10, size=(3,4))
x2 # 2차원

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [7]:
x3 = np.random.randint(10, size=(3,4,5))
x3 # 3차원

array([[[4, 1, 7, 3, 2],
        [4, 7, 2, 4, 8],
        [0, 7, 9, 3, 4],
        [6, 1, 5, 6, 2]],

       [[1, 8, 3, 5, 0],
        [2, 6, 2, 4, 4],
        [6, 3, 0, 6, 4],
        [7, 6, 7, 1, 5]],

       [[7, 9, 2, 4, 8],
        [1, 2, 1, 1, 3],
        [5, 9, 0, 8, 1],
        [6, 3, 3, 5, 9]]])

In [ ]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
# 수직 쌓기
np.vstack([x,grid])

In [ ]:
y = np.array([[99],[99]])
# 수평 쌓기
np.hstack([grid, y])

In [ ]:
grid = np.arange(16).reshape((4,4))
grid

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(data = [[1,2,3],[4,5,6]], columns = ['A', 'B', 'C'])

In [11]:
df

A  B  C
0  1  2  3
1  4  5  6

## Series 매서드

#### Series 메서드

head() : 데이터일부를표시<br>
value_counts() : 고유값의빈도수계산(Series만지원) / normalize=True로설정하면상대빈도<br>
size, shape, len(x) : 원소개수계산<br>
count():결측치를제외한개수<br>
min(), max(), mean(), median(), std(), sum()<br>
describe() : 요약통계량제공(개수, 평균, 표준편차, 최소값, 4분위수, 최대값)<br>
quantile() : 정확한분위수계산<br>
isnull():결측치체크<-> notnull()<br>
fillna() : 결측치를한번에특정값으로변환<br>
dropna() : 결측치제거<br>
hasnans: 하나라도결측치가있으면True (Series만지원)<br>
astype() : 데이터형식변경(결측치가있는경우오류)<br>


In [16]:
# 가장 유용한 메서드, 
df['A'].value_counts()

1    1
4    1
Name: A, dtype: int64