# NumPy

## 리스트 
 - 여러개의요소를담는가변적인표준컨테이너
 - 서로 다른 데이터 타입의 요소를 담는 리스트 생성 가능
 - 단점: 행렬연산등 처리의 어려움

In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [3]:
L2 = [True, '2', 3.0, 4]
L2

[True, '2', 3.0, 4]

In [4]:
[type(item) for item in L2]

[bool, str, float, int]

In [5]:
for item in L2:
    print(type(item))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


### NumPy 패키지를 사용하여 행렬 연산 및 처리가 가능한 배열(Array) 생성
 - NumPy는 배열의 모든 요소가 같은 타입
 - 타입이 일치하지 않으면 NumPy는 가능한 경우 상위타입을 취함
 - dypte키워드를 사용하여 데이터 타입 설정도 가능
 - 리스트의 중첩을 통해 다차원배열 생성 가능

In [6]:
import numpy as np

In [7]:
np.array([1,4,5,3])

array([1, 4, 5, 3])

In [8]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
np.array([[2,3,4],[5,6,7],[8,9,'10']])

array([['2', '3', '4'],
       ['5', '6', '7'],
       ['8', '9', '10']], dtype='<U11')

In [11]:
# 0으로 채운 길이 10의 정수 배열
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 1로 채운 3*5 배열
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# 0과 1 사이에 일정한 간격을 지닌 다섯개의 값
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((10))

array([0.72966708, 0.74120504, 0.33599136, 0.99726839, 0.82435247,
       0.01370892, 0.13935928, 0.13351544, 0.17738085, 0.30312593])

In [18]:
# 0과 1사이의 난수로 구성된 3*3 배열
np.random.random((3,3))

array([[0.79022298, 0.14921658, 0.14125602],
       [0.36386456, 0.77759495, 0.58962052],
       [0.55958162, 0.58353751, 0.84987723]])

In [19]:
# 정규분포(평균=0, 표준편차=1)의 난수로 구성된 3*3 배열
np.random.normal(0,1,(3,3))

array([[-0.51836918, -0.44282604,  1.28482442],
       [-0.563159  , -1.08743539, -1.42035277],
       [ 0.7396375 ,  0.90836807,  0.43222873]])

In [20]:
# 0과 10 사이의 정수 난수로 구성된 3*3배열
np.random.randint(0, 11, (3,3))

array([[ 3, 10, 10],
       [10,  3,  2],
       [10,  3,  9]])

### NumPy 내장 루틴 : 사전 정의된 배열 사용

In [21]:
# 3*3 단위 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# 3개의 정수를 가지는 초기화되지 않은 배열 만들기
np.empty(3)

array([1., 1., 1.])

In [ ]:
# NumPy 데이터 타입
# bool : 1바이트로 저장된 bool 값 (참 또는 거짓)
# int : int64 또는 int32
# Int8 : 바이트(-128~127)
# int16 : 정수(-32768~32767)
# int32 : 정수(-2147483648~2147483647)
# int64 : 정수(-9223372036854775808~9223372036854775807)
# unit8 : 부호없는정수(0~255)
# unit16 : 부호없는정수(0~65535)
# unit32 : 부호없는정수(0~4294967295)
# unit64 : 부호없는정수(0~18446744073709551615)
# float : float64
# float16 : 반정밀부동소수점,5비트지수,10비트가수
# float32 : 단정밀부동소수점,8비트지수,32비트가수
# float64 : 배정밀부동소수점,11비트지수,53비트가수
# complex : complex128
# complex64 : 복소수,두개의32비트부동소수점으로표현
# complex128 : 복소수,두개의64비트부동소수점으로표현

In [25]:
np.random.seed(123)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[4, 1, 7, 3, 2],
        [4, 7, 2, 4, 8],
        [0, 7, 9, 3, 4],
        [6, 1, 5, 6, 2]],

       [[1, 8, 3, 5, 0],
        [2, 6, 2, 4, 4],
        [6, 3, 0, 6, 4],
        [7, 6, 7, 1, 5]],

       [[7, 9, 2, 4, 8],
        [1, 2, 1, 1, 3],
        [5, 9, 0, 8, 1],
        [6, 3, 3, 5, 9]]])

In [26]:
# 배열 속성 지정
print(x3.ndim) # 차원의 개수
print(x3.shape) # 각 차원의 크기
print(x3.size) # 전체 배열의 크기
print(x3.dtype) # 데이터 타입
print(x3.itemsize) # 배열 요소의 크기(바이트 단위)
print(x3.nbytes) # 배열의 전체 크기(바이트 단위)

3
(3, 4, 5)
60
int32
4
240


In [27]:
x1

array([2, 2, 6, 1, 3, 9])

In [28]:
print(x1[0])
print(x1[-1])

2
9


In [29]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [30]:
print(x2[0,0])
print(x2[1,-1])

6
9


In [31]:
# 배열 슬라이싱
x = np.arange(10)
print(x)
print(x[5:])
print(x[4:7])
print(x[0:2])
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[4 5 6]
[0 1]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [32]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [33]:
x2[:2, :3]

array([[6, 1, 0],
       [9, 0, 0]])

In [34]:
x2[:,0]

array([6, 9, 3])

In [35]:
x2_sub = x2[:2, :2]
x2_sub

array([[6, 1],
       [9, 0]])

In [36]:
x2_sub[0,0]=99
x2_sub

array([[99,  1],
       [ 9,  0]])

In [37]:
x2

array([[99,  1,  0,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

In [38]:
x2_sub = x2[:2, :2].copy()
x2_sub

array([[99,  1],
       [ 9,  0]])

In [39]:
x2_sub[0,0]=42
x2_sub

array([[42,  1],
       [ 9,  0]])

In [40]:
x2

array([[99,  1,  0,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

### 배열 재구조화(형상 변경)
 - reshape() 메소드를 사용
 - 1차원 배열을 2차원 행이나 열 매트릭스로 전환하는 경우에는 슬라이스 연산 내에 newaxis 키워드 사용

In [41]:
grid = np.arange(1,10)
x = np.array([1,2,3])
print(grid)
print(x)

[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [42]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [43]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [44]:
# 배열 결합
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [45]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [46]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
# 첫번째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# 두번째 축을 따라 연결
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
# 수직 쌓기
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
y = np.array([[99],[99]])
# 수평 쌓기
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [53]:
# 하나의 배열을 여러 개로 분할
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [ 4 99] [99  3  2  1]


In [54]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [56]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 1. 출력 지정

In [57]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y

array([ 0., 10., 20., 30., 40.])

In [58]:
y = np.zeros(10)
np.power(2, x, out = y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [59]:
## 1. 출력 지정

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y

y = np.zeros(10)
np.power(2, x, out = y[::2])

array([ 1.,  2.,  4.,  8., 16.])

## 2. 집계

In [60]:
x = np.arange(1,10)
np.add.reduce(x)

45

In [61]:
np.multiply.reduce(x)

362880

In [62]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [63]:
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)